//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almentor_XamarinApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Splashscreen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Splashscreen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almentor_XamarinApp.Resx.Splashscreen", typeof(Splashscreen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string btn_nav {
            get {
                return ResourceManager.GetString("btn_nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي .
        /// </summary>
        internal static string BtnLanguage {
            get {
                return ResourceManager.GetString("BtnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicResource Gray-Black.
        /// </summary>
        internal static string BtnLanguageColor {
            get {
                return ResourceManager.GetString("BtnLanguageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show All.
        /// </summary>
        internal static string BtnProdct {
            get {
                return ResourceManager.GetString("BtnProdct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Lable_welcom {
            get {
                return ResourceManager.GetString("Lable_welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string lbl_details {
            get {
                return ResourceManager.GetString("lbl_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show All.
        /// </summary>
        internal static string LblAllProduct {
            get {
                return ResourceManager.GetString("LblAllProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almentor_XamarinApp.Images.Icon.souqLogoEn.png.
        /// </summary>
        internal static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almentor_XamarinApp.Images.Icon.LogoEn.png.
        /// </summary>
        internal static string Logo_ {
            get {
                return ResourceManager.GetString("Logo_", resourceCulture);
            }
        }
    }
}
